### ISSUE TITLE
Build component page

### ISSUE THREAD

**Issue by agazso** [diete-design/diete.design#31]
The page to display components

Missing components:
- [x] Typography #14 
- [x] Tab bar #35 
- [x] Select vertical layout #30 
- [x] Code preview #32 
- [x] Color/theme picker #33
- [x] List menu for the sidebar #34 

https://www.figma.com/file/SIfBIOnc6qmVOJ73q42IMp/diete.design-website?type=design&node-id=4-642&mode=design&t=kAM5ID8U7rq7hLMs-4
